django_project/django_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from lactancia import views
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
   
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('lactancia.urls', namespace="lactancia")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('ratings.urls')),
    url(r'^select2/', include('django_select2.urls')),
)

    

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
              {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', 
              {'document_root': settings.STATIC_ROOT}),   
        ) + static('/', document_root='static/')

django_project/lactancia/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
## EN CASTELLANO
    # ex: /
    url(r'^$', views.landing, name='landing'),
    url(r'^buscar/$', views.buscar, name='buscar'),
    url(r'^cookies/$', views.cookies, name='cookies'),
    url(r'^privacidad/$', views.privacidad, name='privacidad'),
    url(r'^aviso_legal/$', views.aviso_legal, name='aviso_legal'),
    url(r'^avales/$', views.avales, name='avales'), 
    url(r'^patrocinadores/$', views.patrocinadores, name='patrocinadores'), 
    url(r'^donativos/$', views.donativos, name='donativos'), 
    url(r'^donativo-exito/$', views.donativo_exito, name='donativo_exito'),
    url(r'^donativo-cancelado/$', views.donativo_cancelado, name='donativo_cancelado'),
    url(r'^newsletter-error/$', views.boletin_error, name='boletin_error'),
    url(r'^gracias-newsletter/$', views.boletin_ok, name='boletin_ok'),
    url(r'^alertas/$', views.alerta_riesgos, name='alerta_riesgos'),
    url(r'^creditos/$', views.creditos, name='creditos'),
    url(r'^lista_negra/$', views.lista_negra, name='lista_negra'),
    url(r'^limpia_cache/$', views.limpia_cache, name='limpia_cache'),
    url(r'^estadisticas/$', views.estadisticas, name='estadisticas'),
    url(r'^estadisticas_ES/$', views.estadisticas_ES, name='estadisticas_ES'),
    url(r'^producto/(?P<producto_id>\d+)/$', views.detalle_p, name='detalle_p'),
    url(r'^breastfeeding/(?P<slug>[\w-]+)/product/$', views.ficha_producto, name='ficha_producto'),
    url(r'^grupo/(?P<grupo_id>\d+)/$', views.detalle_g, name='detalle_g'),
    url(r'^breastfeeding/(?P<slug>[\w-]+)/group/$', views.ficha_grupo, name='ficha_grupo'),
    url(r'^marca/(?P<marca_id>\d+)/$', views.detalle_m, name='detalle_m'),
    url(r'^breastfeeding/(?P<slug>[\w-]+)/tradename/$', views.ficha_marca, name='ficha_marca'),
    url(r'^sinonimo/(?P<alias_id>\d+)/$', views.detalle_ap, name='detalle_ap'),
    url(r'^breastfeeding/(?P<slug>[\w-]+)/synonym/$', views.ficha_alias, name='ficha_alias'),
    url(r'^otra_escritura/(?P<otra_escritura_id>\d+)/$', views.detalle_oe, name='detalle_oe'),
    url(r'^breastfeeding/(?P<slug>[\w-]+)/writing/$', views.ficha_otra_escritura, name='ficha_otra_escritura'),
    url(r'^download-citation/$', views.download_citation, name='download_citation'),
    url(r'^API/get_list_of_terms$', views.get_list_of_terms, name='get_list_of_terms'),
    url(r'^API/get_date_last_update_list_of_terms$', views.get_date_last_update_list_of_terms, name='get_date_last_update_list_of_terms'),
    url(r'^API/get_term/(?P<prod_id>\d+)$', views.get_term, name='get_term'),
    
    
]

'''
    # url(r'^resultado$', views.primer_resultado, name='primer_resultado'),
    # 
    # 
    # url(r'^estadisticas$', views.estadisticas, name='estadisticas'),
    # url(r'^estadisticas_ES$', views.estadisticas_ES, name='estadisticas_ES'),
    # url(r'^lista_negra$', views.lista_negra, name='lista_negra'),
    # url(r'^donativos$', views.donativos, name='donativos'),
    # url(r'^donativo_exito$', views.donativo_exito, name='donativo_exito'),
    # url(r'^donativo_cancelado$', views.donativo_cancelado, name='donativo_cancelado'),
    # url(r'^boletin_error$', views.boletin_error, name='boletin_error'),
    # url(r'^cookies_es$', views.cookies_es, name='cookies_es'),
    # url(r'^privacidad$', views.privacidad, name='privacidad'),
    # 

'''
'''                   
    # ex: /detalleproducto/5/
    url(r'^producto/(?P<producto_id>\d+)$', views.detalle_p, name='detalle_p'),
    # ex: /detalle_alias/5/
    url(r'^alias_es/(?P<alias_id>\d+)$', views.detalle_ap, name='detalle_ap'),
    # ex: /detale_grupo/5/
    url(r'^grupo/(?P<grupo_id>\d+)$', views.detalle_g, name='detalle_g'),
    # ex: /detalle_marca/5/
    url(r'^marca/(?P<marca_id>\d+)$', views.detalle_m, name='detalle_m'),
'''                   


django_project/lactancia/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.template.defaultfilters import date as _date
from django.utils.html import mark_safe
from django.db.models import signals
from django.core.validators import MaxValueValidator, MinValueValidator
import re
import unidecode

def slugify(text):
    text = unidecode.unidecode(text).lower()
    text = re.sub(r'\W+', ' ', text).strip()
    return re.sub(r'\W+', '-', text)

PROFILE_CHOICES = (
                ('1', _(u'Pediatra')),
                ('2', _(u'Ginecóloga/o')),
                ('14', _(u'Médico de familia')),
                ('3', _(u'Otra especialidad médica')),
                ('4', _(u'Matrona')),
                ('5', _(u'Enfermera/o')),
                ('13', _(u'Farmacéutico/a')),
                ('6', _(u'Otro sanitario')),
                ('7', _(u'Consultora lactancia (IBCLC, OMS)')),
                ('8', _(u'Grupo de apoyo')),
                ('9', _(u'Doula')),
                ('10', _(u'Madre/Padre')),
                ('11', _(u'Otro')),
                ('12', _(u'Anónimo')),
                )

class Grupo(models.Model):
    nombre = models.CharField(_(u'Nombre'), db_index=True, max_length=255, unique=True)
    slug = models.SlugField(max_length=100, verbose_name=_(u'Slug'), help_text=_(u'Es parte de la URL. Se crea automáticamente a partir del nombre del grupo en inglés. El sistema se asegurará de que sea único. Ejemplo: Anti-dementia Drug -> anti-dementia-drug  http://e-lactancia/breastfeeding/anti-dementia-drug/group/.'), unique= False)
    fecha_creacion = models.DateTimeField(_(u'Fecha de creación'),auto_now_add = True)
    fecha_modificacion = models.DateTimeField(_(u'Última modificación'), db_index=True, auto_now = True)
    relacionados = models.ManyToManyField('self', blank=True, verbose_name=_(u'grupos con los que se relaciona'))

    class Meta:
        verbose_name = _(u'Grupo')
        verbose_name_plural = _(u'Grupos')
        ordering=['nombre',]
        
    def traducido_al_ingles(self):
        return self.nombre_en != self.nombre_es

    traducido_al_ingles.boolean = True
    traducido_al_ingles.admin_order_field = 'nombre'
    traducido_al_ingles.short_description=_(u'Traducido')
    
    def obten_relacionados(self):
        return ";\n".join([g.nombre for g in self.relacionados.all()])
    obten_relacionados.short_description= _(u'Grupos relacionados')

    def hay_relacionados(self):
        return (self.relacionados.count() > 0)
    hay_relacionados.boolean = True
    hay_relacionados.short_description= _(u'Hay grupos relacionados')

    def num_productos(self):
        return Producto.objects.filter(grupo=self.id).count()
    num_productos.short_description= _(u'Nº productos')

    def visitas(self):
        aux = Visita_grupo_total.objects.filter(grupo=self.id)
        if len(aux) > 0:
            return aux[0].visitas
        return None
    visitas.short_description= _(u'Nº visitas')

    def opiniones_pendientes(self):
        filterargs = { 'grupo': self.id, 'leido': False }
        return Comentario.objects.filter(**filterargs).count()>0
    opiniones_pendientes.boolean = True
    opiniones_pendientes.short_description= _(u'Nuevas opiniones')

    def dime_que_eres(self):
        return u'grupo'

    # returns Absolute url. Example: http://e-lactancia.org/breastfeeding/contraceptive-pills-3-days/product/
    def get_absolute_url(self):
        return "/breastfeeding/%s/group/" % self.slug
    
    def __unicode__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        nombre = getattr(self, 'nombre_en', None)
        if nombre is None or nombre == u'':
            nombre = getattr(self, 'nombre_es', None)
        
        if nombre is not None:
            ### Estos pasos son necesarios para garantizar que el slug sea único para cada término:
            slug = slugify(nombre)[0:93]
            id = getattr(self, 'id', None)
            duplicated_slug = Grupo.objects.filter(slug=slug).exclude(id=id).count()
            if duplicated_slug>0:
                slug = slug + '-' + str(duplicated_slug + 1)
                
            setattr(self, 'slug', slug)
            
        super(Grupo, self).save(*args, **kwargs)   
        
        
        
class Riesgo(models.Model):
    nivel = models.IntegerField(unique=True)
    nombre = models.CharField(_(u'Nombre'), max_length=200)
    descripcion = models.CharField(_(u'Descripción'), max_length=500)
    
    def num_productos(self):
        return Producto.objects.filter(riesgo=self.id).count()
    num_productos.short_description= _(u'Número de productos')

    def dime_que_eres(self):
        return u'riesgo'
        

    def __unicode__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(db_index=True, max_length=255, verbose_name=_(u'Nombre'), unique=True)
    slug = models.SlugField(max_length=100, verbose_name=_(u'Slug'), help_text=_(u'Es parte de la URL. Se crea automáticamente a partir del nombre del producto en inglés. El sistema se asegurará de que sea único. Ejemplo:  Acetylcysteine -> acetylcysteine para http://e-lactancia/breastfeeding/acetylcysteine/product.'), unique= False)
    grupo = models.ManyToManyField('grupo')
    riesgo = models.ForeignKey('riesgo', verbose_name=_(u'Nivel de riesgo'))
    comentario = models.CharField(max_length = 10000, blank=True, null=True, verbose_name=_(u'Comentario'))
    no_alternativas = models.BooleanField(default=False, verbose_name=_(u'No puede tener alternativas'), help_text=_(u'Marca esta casilla si no tiene sentido que el término tenga altenativas. Por ejemplo, una enfermedad congénita o adquirida.'))
    alternativas = models.ManyToManyField('self', blank=True, symmetrical=False, verbose_name=_(u'Lista de productos alternativos'))
    referencia_otros_productos = models.ManyToManyField('self', blank=True, symmetrical=False, verbose_name=_(u'Referencia a otros productos'), help_text=_(u'Aparecerá un enlace a las fichas de estos productos en la caja de comentario.'), related_name='referenciados')
    referencia_grupos = models.ManyToManyField('grupo', blank=True, symmetrical=False, verbose_name=_(u'Referencia a grupos de productos'), help_text=_(u'Aparecerá un enlace a las fichas de estos grupos en la caja de comentario.'), related_name='grupos_referenciados')
    tiene_biblio = models.BooleanField(default=True, verbose_name=_(u'Tiene bibliografia (añadida o pendiente de añadir)'), help_text=_(u'Indica si el producto poseera referencias bibliográficas. Si no las va a tener ni ahora ni en el futuro, debe desmarcarse esta casilla. Ejemplos de productos que pueden no tener bibliografía asociada son los de Fitoterapia'))
    biblio = models.ManyToManyField('Bibliografia',verbose_name=_(u'bibliografia'),blank=True)
    csvfile = models.FileField(upload_to='papers/%Y/%m/', verbose_name=_(u'Importar biblio con fichero CSV'), blank=True)
    marcas = models.ManyToManyField('Marca',verbose_name=_(u'Listado de marcas comerciales'),blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add = True, verbose_name=_(u'Fecha de creación'))
    fecha_modificacion = models.DateTimeField(db_index=True, auto_now = True, verbose_name=_(u'Última modificación'))
    biodisponibilidad = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Biodisponibilidad'))
    peso_molecular = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Peso molecular'))
    union_proteinas = models.CharField(max_length=30, verbose_name=_(u'Unión a proteínas'), blank=True, null=True)
    volumen_distrib = models.CharField(max_length=30, verbose_name=_(u'Volumen de distribución'), blank=True, null=True,)
    pka = models.CharField(max_length=30, verbose_name=_(u'pKa'), blank=True, null=True,)
    t_maximo = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Tiempo máximo, Tmax'))
    t_medio = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Semivida de eliminación, Tiempo medio, T1/2'))
    indice_leche_plasma = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Índice Leche/Plasma'))
    dosis_teorica = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Dosis teórica'))
    dosis_relativa = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Dosis relativa'))
    dosis_terapeutica = models.CharField(max_length=30, blank=True, null=True, verbose_name=_(u'Dosis relativa pediátrica'))
    
    def traducido_al_ingles(self):
        return self.comentario_es != self.comentario_en
    traducido_al_ingles.boolean = True
    traducido_al_ingles.admin_order_field = 'nombre'
    traducido_al_ingles.short_description=_(u'Traducido')

    def hay_alias(self):
        return (self.alias_set.count() > 0)
    hay_alias.boolean=True
    hay_alias.short_description=_(u'Hay alias')
    
    def hay_escrituras(self):
        return (self.otras_escrituras_set.count() > 0)
    hay_escrituras.boolean=True
    hay_escrituras.short_description=_(u'Hay escrituras')


    def hay_alternativas(self):
        return (self.alternativas.count() > 0)
    hay_alternativas.boolean=True
    hay_alternativas.short_description=_(u'Hay alternativas')

    def hay_biblio(self):
        return (self.biblio.count() > 0)
    hay_biblio.boolean=True
    hay_biblio.short_description=_(u'Tiene biblio')

    def num_biblio(self):
        return (self.biblio.count())
    num_biblio.short_description=_(u'Nº refs. bibliográficas')
    
    def biblio_en_vancouver(self):
        for b in self.biblio.all():
            if b.tiene_detalle() == False:
                return False
        return True
    biblio_en_vancouver.boolean=True

django_project/lactancia/forms.py
# -*- coding: utf-8 -*-
from django.forms import Form, ChoiceField, CharField, Textarea, TextInput, Select, RadioSelect, EmailField, ValidationError
from django.core.validators import validate_email
from django.utils.translation import ugettext_lazy as _

PROFILE_CHOICES = (
                ('1', _(u'Pediatra')),
                ('2', _(u'Ginecóloga/o')),
                ('14', _(u'Médico de familia')),
                ('3', _(u'Otra especialidad médica')),
                ('4', _(u'Matrona')),
                ('5', _(u'Enfermera/o')),
                ('13', _(u'Farmacéutico/a')),
                ('6', _(u'Otro sanitario')),
                ('7', _(u'Consultora lactancia (IBCLC, OMS)')),
                ('8', _(u'Grupo de apoyo')),
                ('9', _(u'Doula')),
                ('10', _(u'Madre/Padre')),
                ('11', _(u'Otro')),
                ('12', _(u'Anónimo')),
                )

class PerfilForm(Form):
    perfil = ChoiceField(widget=RadioSelect, choices=PROFILE_CHOICES)
    #perfil = ChoiceField(widget=Select(attrs={'onchange': 'this.form.submit();'}), choices=PROFILE_CHOICES, )
    #perfil = ChoiceField(widget=RadioSelect(attrs={'onchange': 'this.form.submit();'}), choices=PROFILE_CHOICES, )

class ComentarioForm(Form):
    comentario = CharField(widget=Textarea(attrs={'class': 'col-xs-12', 'rows': 5, 'id':"opinion", 'maxlength':250,  'placeholder': _(u"Ayúdanos a mejorar el contenido de e-lactancia con tu opinión o sugerencia sobre la calidad de la información de esta ficha.")}))
    email = EmailField(required=False)
    
    def clean_comentario(self):
        comentario = self.cleaned_data['comentario']
        num_words = len(comentario.split())
        if num_words < 1:
            raise ValidationError(_(u"No hay suficiente texto"))
        return comentario


class Subscription(Form):
    nombre = CharField(widget=TextInput(attrs={'id':"newsletter_nombre", 'maxlength':255,  'placeholder': _(u"Nombre")}),required=True)
    email = EmailField(widget=TextInput(attrs={'id':"newsletter_email", 'maxlength':255, 'placeholder': _(u"Correo electrónico")}),required=True)


my_default_errors = {
    'required': _(u'Este campo es obligatorio'),
    'max_length':_(u'El texto es demasiado largo'),
    'invalid': _(u'Introduzca una dirección de correo válida')
}


django_project/lactancia/templates/lactancia/avales.html
{% extends "lactancia/base.html" %} 
{% load i18n %}
{% block title %}{% trans "Entidades que recomiendan el uso de e-lactancia" %}{% endblock %}

{# share block #}
{% block fb_url %}{% url 'lactancia:avales' %}{% endblock %}
{% block fb_url_top %}{% url 'lactancia:avales' %}{% endblock %}
{% block twitter_data-text %}{% trans "e-lactancia.org está avalada por importantes entidades que recomiendan su uso. Tú también puedes usarla y promocionar la #Lactancia" %}{% endblock %}
{% block twitter_data-text_top %}{% trans "e-lactancia.org está avalada por importantes entidades que recomiendan su uso. Tú también puedes usarla y promocionar la #Lactancia" %}{% endblock %}

{% block titulo_mainpage %}
<h1 class="center">{% block dona_header %}{% trans "Entidades que recomiendan el uso de e-lactancia" %}{% endblock%}</h1>
{% endblock%}



{% block mainpage %}
<div class="row-fluid">
        <div class="risk empty-space risk-miniblock  span12"></div>
</div>
{% for aval in avales %}
<div id="{{aval.id}}" style="margin-bottom:120px;"></div>
<div class="row-fluid"> 
  
  <div class="span4" >
    <p class="text-right"><img class="logo" src="{{aval.logo.url}}"></p>
    <p  class="text-right">{{aval.URL}}</p>
  </div>

  <div class="span6">
    <h2 class="h3">{{aval.entidad}} {% if aval.pais %}({{aval.pais.nombre}}){% endif %}</h2>
    <blockquote >
        <p>{{aval.extracto|safe}}</p>
        <footer><a href="{{aval.carta.url}}" target="_blank"><cite>{% trans 'Leer documento completo' %}</cite></a></footer>
    </blockquote>
  </div> {# de todos los supporters #}  
</div>
<div class="row-fluid">
        <div class="risk empty-space risk-miniblock  span12"></div>
</div>
{% endfor %}
<div class="row-fluid">
        <div class="risk empty-space risk-miniblock  span12"></div>
</div>
{% for t in textos %}
    {% if t.visible %}
    <div class="row"> 
       <div class="span8 offset2">
            <h2 class="text-center">{{t.title}}</h2>
            {{ t.content|safe|linebreaks}}
       </div>
    </div>
    {% endif %}
{% endfor %}
<div class="row-fluid">
        <div class="risk empty-space risk-miniblock  span12"></div>
</div>


{% endblock %}

django_project/lactancia/templates/lactancia/detalle_m.html
{% extends "lactancia/detalle_p.html" %} 
{% load i18n %}
{% block title %}{% trans "Compatibilidad de" %} {{marcap.nombre}} {% trans "con la lactancia materna" %}{% endblock %}

{# share block #}
{% block fb_url %}{% url 'lactancia:detalle_m' marcap.id %}{% endblock %}
{% block fb_url_top %}{% url 'lactancia:detalle_m' marcap.id %}{% endblock %}
{% block twitter_text %}{% trans "Comprueba la compatibilidad de" %} {{marcap.nombre}} {% trans "con la #lactancia" %}{% endblock %}
{% block twitter_text_top %}{% trans "Comprueba la compatibilidad de" %} {{marcap.nombre}} {% trans "con la #lactancia" %}{% endblock %}


{% block modal_newletter %}
{% include 'lactancia/partial_newsletter_marca.html' %}
{% endblock %}


{% block prod_header %}{{ marcap.nombre }}&trade;{% if marcap.nombre != marcap.nombre_paises %} {{ marcap.print_paises }}{% endif %}{% endblock %}
{% block alternativa_no_razon %}{{marcap.nombre}}{% endblock %}
{% block alternativa_no_sin_razon %}{{marcap.nombre}}{% endblock %}


{% block alert %}
{% if marca_alerts %}
    {% for a in marca_alerts.all %}
        {% if a.active_90 %}
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>    
                    <h5><a href="{% url 'lactancia:ficha_producto' a.producto.slug %}">{{ a.producto.nombre }}</a> ({% trans "principio activo de " %} {{marcap.nombre}}): {{a.titulo | safe}}</h5>
                    <p><small>{{a.contenido | safe}}</small></p>
                    <p><small>{% trans "Nivel de riesgo revisado el" %} {{ a.fecha_modificacion|date:"DATE_FORMAT"}}</small></p>
                </div>
        {% endif %}  
    {% endfor %}   
{% endif %}
{% endblock %}




{% block comentario_content %}
    {% block comentario_marca %}
        {% if marcap.paises.all|length > 0 %}
            <p>{% trans "Marca comercializada en " %} 
            {% for p in marcap.paises.all %}
                {{p.nombre}}{% if forloop.last%}. {% else %}, {% endif %}
            {% endfor %}
            </p>
        {% endif %}
    {% endblock %}
    
    {% if marcap.principios_activos.count > 1 %}
        <p>{% block principios_content_plural %}<strong>{{marcap.nombre}}</strong> {% trans "es una marca comercial que contiene en su composición los siguientes principios activos" %}:{% endblock %}</p>
        
    {% else %}
        <p>{% block principios_content_singular %}<strong>{{marcap.nombre}}</strong> {% trans "es una marca comercial que contiene en su composición el siguiente principio activo" %}:{% endblock %}</p>
    {% endif %}
    <ul>
        {% for p in marcap.principios_activos.all|dictsort:"nombre" %}
            <li class="lead"><a {% if prod.riesgo.nivel == 0 %}
                class="link_r0" 
            {% elif prod.riesgo.nivel == 1 %}
                class="link_r1"
            {% elif prod.riesgo.nivel == 2 %}
                class="link_r2"
            {% elif prod.riesgo.nivel == 3 %}
                class="link_r3"
            {% endif %} href="{% url 'lactancia:ficha_producto' p.slug %}"><strong>{{ p.nombre }}</strong></a> ({{p.riesgo.nombre}})</li>
        {% endfor %}
    </ul>
    <strong>{% block marca_disclaimer %}{{ marca_info_disclaimer.contenido |linebreaks }}{% endblock %}</strong>
    
    {% block ojo_con_las_marcas_de_distintos_paises %}<p><em>{% trans "Nota: La composición de algunas marcas varía según países. Asegúrate que esta es la composición de la marca que buscas" %}.</em></p>{% endblock %}
{% endblock %}


{% block alternativas %}
    {% if marcap.principios_activos.count > 1 %}
        <h4>{% block alter_header_marca %}{% trans "Alternativas de cada principio activo" %}{% endblock %}</h4>
        {% for p in marcap.principios_activos.all|dictsort:"nombre" %}

            <h5> {{p.nombre}} </h5>
                {% if p.hay_alternativas %}
                    <ul>
                        {% for alt in p.alternativas.all %}
                            <li class="risk-level{{alt.riesgo.nivel}}-prods" >{% block alter_content %}<a href="{% url 'lactancia:ficha_producto' alt.slug %}"  >{{ alt.nombre }}</a> ({{alt.riesgo.nombre}}){% endblock %}</li>
                        {% endfor %}
                    </ul>
                {% else %}

                    {% if p.riesgo.nivel == 0 %}
                        <p class="risk-level0-prods">{% block alter_no0_marca %}{% trans "No hay alternativas porque tiene nivel de riesgo muy bajo" %}.{% endblock %}</p>
                    {% else %}
                        <p>{% block alter_no %}{% trans "No disponemos de alternativas para" %} <strong>{{p.nombre}}</strong>.{% endblock %}</p>
                    {% endif %}
                {% endif %}
        {% endfor %}   

    {% else %} 
        {{ block.super }}
    {% endif %}
{% endblock %}
        




{% block names_and_biblio %}
{% endblock %}



{% block pharma_popovers %}
{% endblock %}

django_project/lactancia/templates/lactancia/detalle_oe.html
{% extends "lactancia/detalle_p.html" %} 
{% load i18n %}
{% block title %}{% trans "Compatibilidad de" %} {{otra_escritura.nombre}} {% trans "con la lactancia materna" %}{% endblock %}

{# share block #}
{% block fb_url %}{% url 'lactancia:detalle_oe' otra_escritura.id %}{% endblock %}
{% block fb_url_top %}{% url 'lactancia:detalle_oe' otra_escritura.id %}{% endblock %}
{% block twitter_text %}{% trans "Comprueba la compatibilidad de" %} {{otra_escritura.nombre}} {% trans "con la #lactancia" %}{% endblock %}
{% block twitter_text_top %}{% trans "Comprueba la compatibilidad de" %} {{otra_escritura.nombre}} {% trans "con la #lactancia" %}{% endblock %}


{% block modal_newletter %}
{% include 'lactancia/partial_newsletter_otra_escritura.html' %}
{% endblock %}



{% block prod_header %}{{ otra_escritura.nombre }}{% endblock %}
{% block alternativa_no_razon %}{{otra_escritura.nombre}}{% endblock %}
{% block alternativa_no_sin_razon %}{{otra_escritura.nombre}}{% endblock %}


        {% block other_names_first %}
        {% if prod_otras_escrituras %}
            <p><strong>{{otra_escritura.nombre}}</strong> {% trans "es" %} <a href="{% url 'lactancia:ficha_producto' prod.slug %}">{{prod.nombre}}</a> {% trans "en" %} {{otra_escritura.escritura.nombre}}. </p>
            {% if prod_otras_escrituras|length > 1 %}
                {% trans "Así se escribe en otros idiomas" %}:
            {% endif %}
            <ul> 
                    {% for alias in prod_otras_escrituras %}
                        {% if otra_escritura.id != alias.id %}
                            <li><a href="{% url 'lactancia:ficha_otra_escritura' alias.slug %}"  >{{ alias.nombre }}</a> ({{alias.escritura.nombre}})</li>
                        {% endif %}
                    {% endfor %}
            </ul>
        {% endif %}
        
        {% endblock %}
         
        {% block other_names_second %}
         {% if prod_alias %}
            <p>{% block alias_text %}<strong>{{otra_escritura.nombre}}</strong> {% trans "también se conoce como" %}{% endblock %}</p>
            <ul> 
                {% block listado_alias %}
                    {% for alias in prod_alias %}
                        <li><a href="{% url 'lactancia:ficha_alias' alias.slug %}"  >{{ alias.nombre }}</a></li>
                    {% endfor %}
                {% endblock %}
            </ul>
         {% endif %}
        {% endblock %}



{% block name_main_prod_otras_escrituras %}{{aliasp.nombre}}{% endblock %}

{% block term_en_marca %}{{otra_escritura.nombre}}{% endblock %}
{% block term_en_marca_composicion %}{{otra_escritura.nombre}}{% endblock %}



{% block term_plural %}{{otra_escritura.nombre}}{% endblock %}
{% block term_singular %}{{otra_escritura.nombre}}{% endblock %}